### ISSUE TITLE
Don't change powershell execution policy

### ISSUE THREAD

**Issue by TheBestPessimist** [eve-community/V-Color-Calibration-Backup#2]
make a bat file, and (if needed run it as admin) 
containing this: `powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0/<name of powershell script>.ps1" -Verb RunAs
`

**Comment by TheBestPessimist** [comment]
%~dp0 means the folder where the script is located. (this implies that .bat and .ps1 are in the same folder)

**Comment by mjhehn** [comment]
I did a little googling around and this easily seemed like the best option, despite my dislike of making scripts that have no purpose than to just run one other script. Should  be fixed in #3
